'use strict';

module.exports = {
  up: async (queryInterface) => queryInterface.bulkInsert('Hogares', [
    {
      id_encuestas: 1,
      amb_excl_trabajo: 0,
      amb_excl_trabajo_c: 0,
      tiene_ademas_cocina: 1,
      tiene_ademas_lavadero: 1,
      tiene_ademas_garage: 0,
      tiene_ademas_dormir: 0,
      tiene_ademas_dormir_c: 0,
      tiene_ademas_trabaj: 1,
      tiene_ademas_trabaj_c: 1,
      este_hogar_es: 9,
      cocinar_pref: 4,
      baño_tipo: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id_encuestas: 2,
      amb_excl_trabajo: 1,
      amb_excl_trabajo_c: 2,
      tiene_ademas_cocina: 0,
      tiene_ademas_lavadero: 0,
      tiene_ademas_garage: 1,
      tiene_ademas_dormir: 1,
      tiene_ademas_dormir_c: 3,
      tiene_ademas_trabaj: 0,
      tiene_ademas_trabaj_c: 0,
      este_hogar_es: 6,
      cocinar_pref: 2,
      baño_tipo: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id_encuestas: 3,
      amb_excl_trabajo: 1,
      amb_excl_trabajo_c: 2,
      tiene_ademas_cocina: 0,
      tiene_ademas_lavadero: 0,
      tiene_ademas_garage: 1,
      tiene_ademas_dormir: 1,
      tiene_ademas_dormir_c: 4,
      tiene_ademas_trabaj: 0,
      tiene_ademas_trabaj_c: 0,
      este_hogar_es: 3,
      cocinar_pref: 1,
      baño_tipo: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id_encuestas: 4,
      amb_excl_trabajo: 0,
      amb_excl_trabajo_c: 0,
      tiene_ademas_cocina: 1,
      tiene_ademas_lavadero: 1,
      tiene_ademas_garage: 0,
      tiene_ademas_dormir: 1,
      tiene_ademas_dormir_c: 3,
      tiene_ademas_trabaj: 1,
      tiene_ademas_trabaj_c: 3,
      este_hogar_es: 1,
      cocinar_pref: 4,
      baño_tipo: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]),
  down: async (queryInterface) => {
     await queryInterface.bulkDelete('Hogares', null, {
      truncate: true,
      cascade: false,
     });
  }
};